name: Blog Publisher

on:
  schedule:
    # Run at 9 AM EST (14:00 UTC) every day
    - cron: '0 14 * * *'
  
  # Manual trigger for testing
  workflow_dispatch:
  
  # Trigger when blog schedule is updated
  push:
    branches:
      - main
    paths:
      - 'content/blog-schedule.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Publish scheduled posts
        run: |
          echo "======================================
"
          echo "Blog Publisher - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "Trigger: ${{ github.event_name }}"
          echo "======================================"
          node scripts/publish-blog.js
        env:
          TZ: 'America/Toronto'
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No posts to publish today"
          else
            git commit -m "📚 Auto-publish blog post for $(TZ='America/Toronto' date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push
            echo "✅ Blog post published successfully!"
          fi