name: Daily Blog Publisher

on:
  schedule:
    # TEST: Run every 5 minutes to verify scheduling works
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run blog publisher
      run: node scripts/publish-blog.js
      env:
        TZ: 'America/Toronto'
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No posts to publish today"
        else
          git commit -m "📚 Auto-publish scheduled blog post for $(date +'%Y-%m-%d')"
          git push
        fi